name: Android Build & Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install build tools
        run: |
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "build-tools;29.0.3"
      

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        
      - name: Build Release APK and Bundle
        run: ./gradlew assembleRelease bundleRelease
        
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        
      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}


      - name: Rename signed APK
        run: |
          mkdir -p renamed
          cp ${{ steps.sign_apk.outputs.signedReleaseFile }} renamed/cupcake.${{ env.VERSION }}.signed.apk
          echo "RENAMED_APK=renamed/cupcake.${{ env.VERSION }}.signed.apk" >> $GITHUB_ENV

      - name: Rename signed Bundle
        run: |
          cp ${{ steps.sign_bundle.outputs.signedReleaseFile }} renamed/cupcake.${{ env.VERSION }}.signed.aab
          echo "RENAMED_BUNDLE=renamed/cupcake.${{ env.VERSION }}.signed.aab" >> $GITHUB_ENV
      

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: ${{ env.RENAMED_APK }}
          
      - name: Upload Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-bundle
          path: ${{ env.RENAMED_BUNDLE }}


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.RENAMED_APK }}
            ${{ env.RENAMED_BUNDLE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
